@extends('layouts.app')

@section('page_title', 'Communication Reports')
@section('content')
<div class="card mb-3"><div class="card-body"><form method="GET" class="form-row"><div class="col-md-4 mb-2"><input type="date" name="date_from" class="form-control" value="{{ $filters['date_from'] ?? '' }}"></div><div class="col-md-4 mb-2"><input type="date" name="date_to" class="form-control" value="{{ $filters['date_to'] ?? '' }}"></div><div class="col-md-4 mb-2"><button class="btn btn-outline-primary btn-block">Apply</button></div></form></div></div>
<div class="row mb-3"><div class="col-md-6"><div class="small-box bg-info"><div class="inner"><h3>{{ $unreadAnnouncementTotal }}</h3><p>Unread announcement records</p></div></div></div><div class="col-md-6"><div class="small-box bg-primary"><div class="inner"><h3>{{ $activeRooms }}</h3><p>Active chat rooms</p></div></div></div></div>
<div class="card mb-3"><div class="card-header">Announcement Engagement</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Announcement</th><th>Read</th><th>Unread</th></tr></thead><tbody>@foreach($engagement as $row)<tr><td>{{ $row->title }}</td><td>{{ $row->read_count }}</td><td>{{ $row->unread_count }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card mb-3"><div class="card-header">Announcements</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>#</th><th>Title</th><th>Status</th><th>By</th></tr></thead><tbody>@foreach($announcements as $announcement)<tr><td>{{ $announcement->announcement_number }}</td><td>{{ $announcement->title }}</td><td>{{ ucfirst($announcement->status) }}</td><td>{{ $announcement->creator?->display_name }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $announcements->links() }}</div></div>
<div class="card"><div class="card-header">Chat Activity</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Date</th><th>Room</th><th>Sender</th><th>Message</th></tr></thead><tbody>@foreach($chatActivity as $message)<tr><td>{{ $message->created_at?->format('Y-m-d H:i') }}</td><td>{{ $message->room?->room_name }}</td><td>{{ $message->sender?->display_name }}</td><td>{{ \Illuminate\Support\Str::limit($message->message_body ?? '[attachment]', 80) }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $chatActivity->links() }}</div></div>
@endsection
