@extends('layouts.app')

@section('page_title', 'Financial Reports')
@section('content')
<div class="card mb-3"><div class="card-body"><form method="GET" class="form-row">
<div class="col-md-2"><input class="form-control" type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}"></div>
<div class="col-md-2"><input class="form-control" type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}"></div>
<div class="col-md-2"><select class="form-control" name="branch_id"><option value="">Branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(($filters['branch_id'] ?? null)==$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
<div class="col-md-2"><select class="form-control" name="category_id"><option value="">Category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id'] ?? null)==$category->id)>{{ $category->category_name }}</option>@endforeach</select></div>
<div class="col-md-2"><select class="form-control" name="user_id"><option value="">User</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(($filters['user_id'] ?? null)==$user->id)>{{ $user->display_name }}</option>@endforeach</select></div>
<div class="col-md-2"><select class="form-control" name="status"><option value="">Status</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div>
<div class="col-md-12 mt-2 text-right"><button class="btn btn-outline-primary">Apply Filters</button> <a class="btn btn-outline-success" href="{{ route('finance.reports.export-csv', request()->query()) }}">Export CSV</a> <a class="btn btn-outline-success" href="{{ route('finance.reports.export-excel', request()->query()) }}">Export Excel</a> <a class="btn btn-outline-danger" href="{{ route('finance.reports.export-pdf', request()->query()) }}" target="_blank">PDF View</a> <a class="btn btn-outline-secondary" href="{{ route('finance.reports.print', request()->query()) }}" target="_blank">Print</a></div>
</form></div></div>

<div class="card mb-3"><div class="card-header">Expense Report</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>No</th><th>Date</th><th>Branch</th><th>Category</th><th>Amount</th><th>Status</th></tr></thead><tbody>@foreach($reports['expenses'] as $expense)<tr><td>{{ $expense->expense_number }}</td><td>{{ optional($expense->expense_date)->format('Y-m-d') }}</td><td>{{ $expense->branch?->name }}</td><td>{{ $expense->category?->category_name }}</td><td>{{ number_format($expense->amount,2) }}</td><td>{{ ucfirst($expense->status) }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $reports['expenses']->links() }}</div></div>
<div class="card mb-3"><div class="card-header">Cash In Report</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>No</th><th>Branch</th><th>Source</th><th>Amount</th></tr></thead><tbody>@foreach($reports['cash_ins'] as $entry)<tr><td>{{ $entry->cash_in_number }}</td><td>{{ $entry->branch?->name }}</td><td>{{ $entry->source_type }}</td><td>{{ number_format($entry->amount,2) }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $reports['cash_ins']->links() }}</div></div>
<div class="card"><div class="card-header">Cash Out Report</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>No</th><th>Branch</th><th>Source</th><th>Amount</th></tr></thead><tbody>@foreach($reports['cash_outs'] as $entry)<tr><td>{{ $entry->cash_out_number }}</td><td>{{ $entry->branch?->name }}</td><td>{{ $entry->source_type }}</td><td>{{ number_format($entry->amount,2) }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $reports['cash_outs']->links() }}</div></div>
@endsection
