@extends('layouts.app')

@section('page_title', 'Inventory Reports')
@section('content')
<div class="card mb-3"><div class="card-body"><form method="GET" class="form-row">
<div class="col-md-3 mb-2"><input type="date" class="form-control" name="date_from" value="{{ $filters['date_from'] ?? '' }}"></div>
<div class="col-md-3 mb-2"><input type="date" class="form-control" name="date_to" value="{{ $filters['date_to'] ?? '' }}"></div>
<div class="col-md-3 mb-2"><select class="form-control" name="branch_id"><option value="">Branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(($filters['branch_id'] ?? null)==$branch->id)>{{ $branch->branch_name ?? $branch->name }}</option>@endforeach</select></div>
<div class="col-md-3 mb-2 text-right"><button class="btn btn-outline-primary">Apply</button> <a class="btn btn-outline-success" href="{{ route('reports.inventory.export-csv', request()->query()) }}">Export CSV</a> <a class="btn btn-outline-secondary" target="_blank" href="{{ route('reports.inventory.print', request()->query()) }}">Print</a></div>
</form></div></div>

<div class="card mb-3"><div class="card-header">Inventory Summary</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Branch</th><th>Product</th><th>Qty</th><th>Reorder</th><th>Value</th></tr></thead><tbody>@foreach($summary as $row)<tr><td>{{ $row->branch?->branch_name ?? $row->branch?->name }}</td><td>{{ $row->product?->product_name }}</td><td>{{ $row->quantity_available }}</td><td>{{ $row->reorder_level }}</td><td>{{ number_format((float) $row->inventory_value,2) }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $summary->links() }}</div></div>
<div class="card mb-3"><div class="card-header">Movement Report</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Date</th><th>Branch</th><th>Product</th><th>In</th><th>Out</th></tr></thead><tbody>@foreach($movements as $movement)<tr><td>{{ $movement->created_at?->format('Y-m-d') }}</td><td>{{ $movement->branch?->branch_name ?? $movement->branch?->name }}</td><td>{{ $movement->product?->product_name }}</td><td>{{ $movement->quantity_in }}</td><td>{{ $movement->quantity_out }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $movements->links() }}</div></div>
<div class="card mb-3"><div class="card-header">Adjustment Report</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>No</th><th>Branch</th><th>Status</th><th>Date</th></tr></thead><tbody>@foreach($adjustments as $adjustment)<tr><td>{{ $adjustment->adjustment_number }}</td><td>{{ $adjustment->branch?->branch_name ?? $adjustment->branch?->name }}</td><td>{{ ucfirst($adjustment->status) }}</td><td>{{ $adjustment->created_at?->format('Y-m-d') }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $adjustments->links() }}</div></div>
<div class="card"><div class="card-header">Transfer Report</div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>No</th><th>From</th><th>To</th><th>Status</th><th>Date</th></tr></thead><tbody>@foreach($transfers as $transfer)<tr><td>{{ $transfer->transfer_number }}</td><td>{{ $transfer->sourceBranch?->branch_name ?? $transfer->sourceBranch?->name }}</td><td>{{ $transfer->destinationBranch?->branch_name ?? $transfer->destinationBranch?->name }}</td><td>{{ ucfirst(str_replace('_',' ',$transfer->status)) }}</td><td>{{ $transfer->created_at?->format('Y-m-d') }}</td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $transfers->links() }}</div></div>
@endsection
