<?php

return [
    'login_page' => env('RMS_LOGIN_PAGE', 'normal'),
    'demo_password' => env('RMS_DEMO_PASSWORD', 'Demo@123456'),
    'employee_demo_password' => env('RMS_EMPLOYEE_DEMO_PASSWORD', 'Emp@123456'),

    'owner_role_code' => env('RMS_OWNER_ROLE_CODE', 'owner'),
    'admin_role_code' => env('RMS_ADMIN_ROLE_CODE', 'super_admin'),
    'global_branch_role_codes' => array_values(array_unique(array_filter([
        env('RMS_OWNER_ROLE_CODE', 'owner'),
        env('RMS_ADMIN_ROLE_CODE', 'super_admin'),
        'admin',
    ]))),

    'default_roles' => [
        ['code' => 'owner', 'name' => 'Owner', 'description' => 'Executive access across all modules'],
        ['code' => 'super_admin', 'name' => 'Super Admin', 'description' => 'System-wide administration access'],
        ['code' => 'branch_manager', 'name' => 'Branch Manager', 'description' => 'Branch operations and approvals'],
        ['code' => 'cashier', 'name' => 'Cashier', 'description' => 'POS and customer-facing transactions'],
        ['code' => 'inventory_staff', 'name' => 'Inventory Staff', 'description' => 'Inventory operations access'],
        ['code' => 'accounting_staff', 'name' => 'Accounting Staff', 'description' => 'Finance and reporting access'],
        ['code' => 'auditor', 'name' => 'Auditor', 'description' => 'Read-only compliance access'],
        ['code' => 'staff_user', 'name' => 'Staff User', 'description' => 'Limited module access'],
    ],

    'permission_catalog' => [
        'dashboard' => ['view_dashboard', 'view_executive_dashboard', 'view_branch_dashboard'],
        'user_management' => ['view_users', 'create_user', 'edit_user', 'deactivate_user', 'reset_user_password'],
        'role_management' => ['view_roles', 'create_role', 'edit_role', 'assign_permissions'],
        'branch_management' => ['view_branches', 'create_branch', 'edit_branch', 'deactivate_branch'],
        'inventory' => [
            'view_inventory',
            'create_product',
            'edit_product',
            'deactivate_product',
            'view_stock_in',
            'create_stock_in',
            'approve_stock_in',
            'view_stock_adjustment',
            'create_stock_adjustment',
            'approve_stock_adjustment',
            'view_inventory_transfer',
            'create_inventory_transfer',
            'approve_inventory_transfer',
            'receive_inventory_transfer',
            'view_physical_count',
            'create_physical_count',
            'view_inventory_reports',
        ],
        'pos' => [
            'view_pos',
            'create_sale',
            'view_sales',
            'apply_discount',
            'manage_payment_methods',
            'hold_transaction',
            'void_sale',
            'approve_void_sale',
            'create_sales_return',
            'approve_sales_return',
            'reprint_receipt',
            'view_sales_dashboard',
        ],
        'airtime' => [
            'view_airtime_dashboard',
            'manage_airtime_providers',
            'view_airtime_wallets',
            'create_airtime_transaction',
            'view_airtime_transactions',
            'create_wallet_funding',
            'approve_wallet_funding',
            'create_wallet_adjustment',
            'approve_wallet_adjustment',
            'reverse_airtime_transaction',
            'view_airtime_reports',
            'export_airtime_reports',
        ],
        'finance' => [
            'view_cash_flow',
            'create_cash_opening',
            'create_cash_in',
            'create_cash_out',
            'view_expenses',
            'create_expense',
            'approve_expense',
            'reject_expense',
            'view_daily_closing',
            'submit_daily_closing',
            'review_daily_closing',
            'manage_fund_transfers',
            'view_financial_ledger',
            'view_financial_reports',
            'export_financial_reports',
        ],
        'warranty' => [
            'view_customers',
            'create_customer',
            'edit_customer',
            'deactivate_customer',
            'view_customer_history',
            'manage_warranty_rules',
            'view_warranties',
            'create_warranty_claim',
            'approve_warranty_claim',
            'reject_warranty_claim',
            'update_warranty_claim_status',
            'manage_warranty_repair',
            'manage_warranty_replacement',
            'view_warranty_reports',
            'export_warranty_reports',
        ],
        'communication' => [
            'view_announcements',
            'create_announcement',
            'edit_announcement',
            'publish_announcement',
            'archive_announcement',
            'view_announcement_reads',
            'access_chat',
            'create_chat_room',
            'manage_chat_room_members',
            'send_chat_message',
            'edit_chat_message',
            'delete_chat_message',
            'view_notification_center',
        ],
        'reports' => ['view_reports', 'export_reports'],
        'security' => ['view_audit_logs', 'view_security_dashboard'],
        'analytics' => [
            'view_sales_reports',
            'view_inventory_reports',
            'view_airtime_reports',
            'view_financial_reports',
            'view_warranty_reports',
            'view_communication_reports',
            'view_audit_reports',
            'manage_dashboard_preferences',
        ],
        'purchasing' => [
            'view_suppliers',
            'manage_suppliers',
            'create_purchase_request',
            'approve_purchase_request',
            'create_purchase_order',
            'approve_purchase_order',
            'receive_purchase_order',
            'view_supplier_payables',
            'record_supplier_payment',
            'manage_office_supplies',
            'view_office_supply_inventory',
            'create_supply_issuance',
            'approve_supply_issuance',
            'view_staff_accountability',
            'view_purchasing_reports',
            'export_purchasing_reports',
        ],
        'approval_security' => [
            'view_approval_inbox',
            'approve_requests',
            'reject_requests',
            'return_requests',
            'manage_approval_rules',
            'view_audit_trail',
            'export_audit_trail',
            'view_security_dashboard',
            'view_login_activity',
            'manage_active_sessions',
            'view_file_access_logs',
            'view_backup_logs',
            'manage_backups',
            'view_security_alerts',
        ],
        'deployment' => [
            'view_deployment_checklists',
            'manage_deployment_checklists',
            'view_data_imports',
            'manage_data_imports',
            'view_training_logs',
            'manage_training_logs',
            'view_go_live_checklists',
            'manage_go_live_checklists',
            'view_support_tickets',
            'manage_support_tickets',
            'view_system_acceptance',
            'manage_system_acceptance',
        ],
        'hrms' => [
            'view_hr_dashboard',
            'view_employees',
            'create_employee',
            'edit_employee',
            'manage_employee_documents',
            'manage_branch_assignment',
            'view_positions',
            'manage_positions',
            'view_schedules',
            'manage_schedules',
            'view_attendance',
            'record_attendance',
            'manage_attendance',
            'view_leave_requests',
            'create_leave_request',
            'review_leave_request',
            'view_overtime_requests',
            'create_overtime_request',
            'review_overtime_request',
            'view_payroll',
            'process_payroll',
            'approve_payroll',
            'release_payroll',
            'view_government_contributions',
            'manage_government_contributions',
            'view_cash_advances',
            'manage_cash_advances',
            'view_employee_loans',
            'manage_employee_loans',
            'view_payslips',
            'generate_payslips',
            'view_hr_reports',
            'export_hr_reports',
        ],
    ],

    'default_settings' => [
        ['key' => 'system.company_name', 'value' => 'RC Store RMS', 'group' => 'branding'],
        ['key' => 'system.currency', 'value' => 'PHP', 'group' => 'regional'],
        ['key' => 'security.session_timeout_minutes', 'value' => '120', 'group' => 'security'],
    ],

    'modules' => [
        ['slug' => 'pos', 'name' => 'POS', 'route' => 'pos.index', 'permission' => 'view_pos', 'screens' => ['Touchscreen POS', 'Receipt Preview', 'Held Transactions']],
        ['slug' => 'inventory', 'name' => 'Inventory', 'route' => 'inventory.index', 'permission' => 'view_inventory', 'screens' => ['Product Masterlist', 'Stock Transfer', 'Movement Ledger', 'Low Stock']],
        ['slug' => 'airtime', 'name' => 'Airtime / Digital Load', 'route' => 'airtime.index', 'permission' => 'view_airtime_dashboard', 'screens' => ['Wallet Balance', 'Funding', 'Load Transactions', 'Airtime Reports']],
        ['slug' => 'cash-flow', 'name' => 'Cash Flow', 'route' => 'cash-flow.index', 'permission' => 'view_cash_flow', 'screens' => ['Opening Cash', 'Daily Closing', 'Cash Variance']],
        ['slug' => 'expenses', 'name' => 'Expenses', 'route' => 'expenses.index', 'permission' => 'view_expenses', 'screens' => ['Expense Encoding', 'Expense Categories', 'Approvals']],
        ['slug' => 'warranty', 'name' => 'Warranty', 'route' => 'warranty.index', 'permission' => 'view_warranties', 'screens' => ['Warranty Lookup', 'Claim Form', 'Status Timeline']],
        ['slug' => 'customers', 'name' => 'Customers', 'route' => 'customers.index', 'permission' => 'view_customers', 'screens' => ['Customer List', 'Customer Profile', 'Purchase History']],
        ['slug' => 'suppliers', 'name' => 'Suppliers', 'route' => 'suppliers.index', 'permission' => 'view_suppliers', 'screens' => ['Supplier Registry', 'Supplier Performance']],
        ['slug' => 'purchasing', 'name' => 'Purchasing', 'route' => 'purchasing.index', 'permission' => 'view_purchasing_reports', 'screens' => ['Purchase Orders', 'Receiving']],
        ['slug' => 'office-supplies', 'name' => 'Office Supplies', 'route' => 'office-supplies.index', 'permission' => 'manage_office_supplies', 'screens' => ['Supplies Catalog', 'Issuance Logs']],
        ['slug' => 'announcements', 'name' => 'Announcements', 'route' => 'announcements.index', 'permission' => 'view_announcements', 'screens' => ['Announcement Feed', 'Read Tracking']],
        ['slug' => 'chat', 'name' => 'Chat', 'route' => 'chat.index', 'permission' => 'access_chat', 'screens' => ['Room List', 'Conversation Panel', 'Notifications']],
        ['slug' => 'reports', 'name' => 'Reports', 'route' => 'reports.index', 'permission' => 'view_reports', 'screens' => ['Sales', 'Inventory', 'Airtime', 'Expenses', 'Warranty', 'Branch']],
        ['slug' => 'approvals', 'name' => 'Approvals', 'route' => 'approvals.index', 'permission' => 'view_approval_inbox', 'screens' => ['Pending Requests', 'Approval Timeline']],
        ['slug' => 'audit-trail', 'name' => 'Audit Trail', 'route' => 'audit-trail.index', 'permission' => 'view_audit_trail', 'screens' => ['Action Ledger', 'IP Tracking']],
        ['slug' => 'users-roles', 'name' => 'Users & Roles', 'route' => 'users-roles.index', 'permission' => 'view_roles', 'screens' => ['User Directory', 'Role Matrix', 'Permission Matrix']],
        ['slug' => 'branches', 'name' => 'Branches', 'route' => 'branches.index', 'permission' => 'view_branches', 'screens' => ['Branch List', 'Branch Profile']],
        ['slug' => 'settings', 'name' => 'Settings', 'route' => 'settings.index', 'permission' => 'settings.view', 'screens' => ['System Settings', 'Security Settings']],
        ['slug' => 'deployment', 'name' => 'Deployment', 'route' => 'deployment.checklists.index', 'permission' => 'view_deployment_checklists', 'screens' => ['Deployment Checklist', 'Data Imports', 'Training Logs', 'Go-Live Checklist', 'Support Tickets', 'Acceptance']],
        ['slug' => 'hr', 'name' => 'HRMS', 'route' => 'hr.dashboard', 'permission' => 'view_hr_dashboard', 'screens' => ['HR Dashboard', 'Employees', 'Scheduling', 'Attendance', 'Payroll', 'Loans']],
    ],

    'owner_metrics' => [
        ['label' => "Today's Sales", 'value' => 'PHP 124,500', 'trend' => '+12.4%'],
        ['label' => 'Monthly Sales', 'value' => 'PHP 2.18M', 'trend' => '+8.2%'],
        ['label' => 'Total Expenses', 'value' => 'PHP 713,440', 'trend' => '-3.1%'],
        ['label' => 'Net Income', 'value' => 'PHP 1.46M', 'trend' => '+10.1%'],
        ['label' => 'Cash Position', 'value' => 'PHP 512,200', 'trend' => '+5.0%'],
        ['label' => 'Inventory Value', 'value' => 'PHP 3.06M', 'trend' => '+1.4%'],
        ['label' => 'Low Stock Items', 'value' => '37', 'trend' => 'Needs action'],
        ['label' => 'Airtime Wallet Balance', 'value' => 'PHP 84,300', 'trend' => '+2.9%'],
        ['label' => 'Pending Approvals', 'value' => '11', 'trend' => 'Urgent'],
        ['label' => 'Warranty Claims', 'value' => '9', 'trend' => '+1'],
        ['label' => 'Unread Announcements', 'value' => '4', 'trend' => 'Review'],
        ['label' => 'Active Branches', 'value' => '6 / 6', 'trend' => 'Stable'],
    ],

    'owner_charts' => [
        'sales_per_branch' => ['labels' => ['Main', 'North', 'South', 'West', 'Online'], 'values' => [450, 320, 270, 300, 420]],
        'sales_trend' => ['labels' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], 'values' => [120, 128, 140, 132, 152, 188, 205]],
        'expense_trend' => ['labels' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], 'values' => [40, 38, 42, 36, 48, 44, 50]],
        'inventory_by_branch' => ['labels' => ['Main', 'North', 'South', 'West', 'Online'], 'values' => [820, 640, 590, 610, 700]],
        'airtime_provider_sales' => ['labels' => ['Provider A', 'Provider B', 'Provider C'], 'values' => [52, 33, 21]],
        'branch_ranking' => ['labels' => ['Main', 'Online', 'North', 'West', 'South'], 'values' => [1, 2, 3, 4, 5]],
    ],

    'owner_tables' => [
        'recent_sales' => [
            ['ref' => 'S-10078', 'branch' => 'Main', 'amount' => 'PHP 1,250'],
            ['ref' => 'S-10077', 'branch' => 'North', 'amount' => 'PHP 980'],
            ['ref' => 'S-10076', 'branch' => 'Online', 'amount' => 'PHP 2,840'],
        ],
        'low_stock' => [
            ['sku' => 'AC-CASE-001', 'item' => 'Clear Case iPhone 13', 'qty' => 4],
            ['sku' => 'LD-REG-100', 'item' => 'Load Card 100', 'qty' => 6],
        ],
        'pending_approvals' => [
            ['type' => 'Expense', 'reference' => 'EXP-2811', 'status' => 'Pending'],
            ['type' => 'Transfer', 'reference' => 'ST-0041', 'status' => 'Pending'],
        ],
        'recent_expenses' => [
            ['reference' => 'EXP-2810', 'category' => 'Utilities', 'amount' => 'PHP 3,240'],
            ['reference' => 'EXP-2809', 'category' => 'Transportation', 'amount' => 'PHP 1,090'],
        ],
        'recent_announcements' => [
            ['title' => 'Month-end inventory count schedule', 'posted_by' => 'Operations'],
            ['title' => 'New POS discount policy reminder', 'posted_by' => 'Finance'],
        ],
    ],

    'branch_metrics' => [
        ['label' => 'Branch Today Sales', 'value' => 'PHP 42,300'],
        ['label' => 'Branch Expenses', 'value' => 'PHP 5,480'],
        ['label' => 'Branch Cash Status', 'value' => 'Balanced'],
        ['label' => 'Branch Inventory Alerts', 'value' => '8 items'],
        ['label' => 'Branch Airtime Wallet', 'value' => 'PHP 12,400'],
        ['label' => 'Branch Pending Tasks', 'value' => '6 tasks'],
        ['label' => 'Branch Daily Closing', 'value' => 'Open'],
    ],
];
