@extends('layouts.app')

@section('page_title', 'Government Contributions')
@section('content')
<div class="row">
    <div class="col-lg-6">
        <div class="card mb-3"><div class="card-header">SSS Table</div><div class="card-body"><form method="POST" action="{{ route('hr.contributions.sss.store') }}" class="form-row">@csrf<div class="col-4 mb-2"><input type="date" name="effective_date" class="form-control" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="salary_from" class="form-control" placeholder="Salary From" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="salary_to" class="form-control" placeholder="Salary To" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="msc" class="form-control" placeholder="MSC" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="employee_share" class="form-control" placeholder="Employee" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="employer_share" class="form-control" placeholder="Employer" required></div><div class="col-12"><button class="btn btn-primary btn-block">Add SSS Row</button></div></form></div><div class="table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Effective</th><th>Range</th><th>Emp</th><th>Er</th></tr></thead><tbody>@forelse($sssRows as $row)<tr><td>{{ optional($row->effective_date)->format('Y-m-d') }}</td><td>{{ number_format((float)$row->salary_from,2) }} - {{ number_format((float)$row->salary_to,2) }}</td><td>{{ number_format((float)$row->employee_share,2) }}</td><td>{{ number_format((float)$row->employer_share,2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No data</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $sssRows->links() }}</div></div>

        <div class="card mb-3"><div class="card-header">Pag-IBIG Table</div><div class="card-body"><form method="POST" action="{{ route('hr.contributions.pagibig.store') }}" class="form-row">@csrf<div class="col-4 mb-2"><input type="date" name="effective_date" class="form-control" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="salary_from" class="form-control" placeholder="Salary From" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="salary_to" class="form-control" placeholder="Salary To" required></div><div class="col-3 mb-2"><input type="number" step="0.0001" min="0" name="employee_rate" class="form-control" placeholder="Emp Rate" required></div><div class="col-3 mb-2"><input type="number" step="0.0001" min="0" name="employer_rate" class="form-control" placeholder="Er Rate" required></div><div class="col-3 mb-2"><input type="number" step="0.01" min="0" name="employee_share" class="form-control" placeholder="Emp Share" required></div><div class="col-3 mb-2"><input type="number" step="0.01" min="0" name="employer_share" class="form-control" placeholder="Er Share" required></div><div class="col-12"><button class="btn btn-primary btn-block">Add Pag-IBIG Row</button></div></form></div><div class="table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Effective</th><th>Range</th><th>Emp</th><th>Er</th></tr></thead><tbody>@forelse($pagibigRows as $row)<tr><td>{{ optional($row->effective_date)->format('Y-m-d') }}</td><td>{{ number_format((float)$row->salary_from,2) }} - {{ number_format((float)$row->salary_to,2) }}</td><td>{{ number_format((float)$row->employee_share,2) }}</td><td>{{ number_format((float)$row->employer_share,2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No data</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $pagibigRows->links() }}</div></div>
    </div>

    <div class="col-lg-6">
        <div class="card mb-3"><div class="card-header">PhilHealth Table</div><div class="card-body"><form method="POST" action="{{ route('hr.contributions.philhealth.store') }}" class="form-row">@csrf<div class="col-4 mb-2"><input type="date" name="effective_date" class="form-control" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="salary_from" class="form-control" placeholder="Salary From" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="salary_to" class="form-control" placeholder="Salary To" required></div><div class="col-4 mb-2"><input type="number" step="0.0001" min="0" name="premium_rate" class="form-control" placeholder="Premium Rate" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="employee_share" class="form-control" placeholder="Employee" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="employer_share" class="form-control" placeholder="Employer" required></div><div class="col-12"><button class="btn btn-primary btn-block">Add PhilHealth Row</button></div></form></div><div class="table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Effective</th><th>Range</th><th>Emp</th><th>Er</th></tr></thead><tbody>@forelse($philhealthRows as $row)<tr><td>{{ optional($row->effective_date)->format('Y-m-d') }}</td><td>{{ number_format((float)$row->salary_from,2) }} - {{ number_format((float)$row->salary_to,2) }}</td><td>{{ number_format((float)$row->employee_share,2) }}</td><td>{{ number_format((float)$row->employer_share,2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No data</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $philhealthRows->links() }}</div></div>

        <div class="card mb-3"><div class="card-header">Withholding Tax Table</div><div class="card-body"><form method="POST" action="{{ route('hr.contributions.tax.store') }}" class="form-row">@csrf<div class="col-4 mb-2"><input type="date" name="effective_date" class="form-control" required></div><div class="col-4 mb-2"><select name="payroll_period_type" class="form-control" required><option value="weekly">Weekly</option><option value="semi_monthly" selected>Semi-Monthly</option><option value="monthly">Monthly</option></select></div><div class="col-4 mb-2"><input type="number" step="0.0001" min="0" name="tax_rate" class="form-control" placeholder="Tax Rate" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="taxable_income_from" class="form-control" placeholder="Taxable From" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="taxable_income_to" class="form-control" placeholder="Taxable To" required></div><div class="col-4 mb-2"><input type="number" step="0.01" min="0" name="base_tax" class="form-control" placeholder="Base Tax" required></div><div class="col-12 mb-2"><input type="number" step="0.01" min="0" name="excess_over" class="form-control" placeholder="Excess Over" required></div><div class="col-12"><button class="btn btn-primary btn-block">Add Tax Row</button></div></form></div><div class="table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Effective</th><th>Type</th><th>Range</th><th>Rate</th></tr></thead><tbody>@forelse($taxRows as $row)<tr><td>{{ optional($row->effective_date)->format('Y-m-d') }}</td><td>{{ ucfirst(str_replace('_',' ',$row->payroll_period_type)) }}</td><td>{{ number_format((float)$row->taxable_income_from,2) }} - {{ number_format((float)$row->taxable_income_to,2) }}</td><td>{{ number_format((float)$row->tax_rate,4) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No data</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $taxRows->links() }}</div></div>
    </div>
</div>
@endsection
