@extends('layouts.app')

@section('page_title', 'Approval Detail')
@section('content')
<div class="card mb-3"><div class="card-body"><div class="row"><div class="col-md-3"><strong>Approval #</strong><div>{{ $approval->approval_number }}</div></div><div class="col-md-3"><strong>Status</strong><div>{{ strtoupper(str_replace('_', ' ', $approval->status)) }}</div></div><div class="col-md-3"><strong>Priority</strong><div>{{ strtoupper($approval->priority) }}</div></div><div class="col-md-3"><strong>Current Approver</strong><div>{{ $approval->currentApprover?->display_name ?? '-' }}</div></div></div><hr><div><strong>Reference:</strong> {{ $approval->reference_type }} #{{ $approval->reference_id }}</div><div><strong>Remarks:</strong> {{ $approval->remarks }}</div></div></div>

<div class="card mb-3"><div class="card-header">Actions</div><div class="card-body"><form method="POST" action="{{ route('approvals.requests.approve', $approval) }}" class="d-inline">@csrf<input name="remarks" class="form-control form-control-sm d-inline-block mr-1" style="width:260px" placeholder="Approval remarks"><button class="btn btn-success btn-sm">Approve</button></form> <form method="POST" action="{{ route('approvals.requests.reject', $approval) }}" class="d-inline">@csrf<input name="rejection_reason" class="form-control form-control-sm d-inline-block mr-1" style="width:260px" placeholder="Rejection reason" required><button class="btn btn-danger btn-sm">Reject</button></form> <form method="POST" action="{{ route('approvals.requests.return', $approval) }}" class="d-inline">@csrf<input name="return_reason" class="form-control form-control-sm d-inline-block mr-1" style="width:260px" placeholder="Return reason" required><button class="btn btn-warning btn-sm">Return</button></form> @if($approval->status === 'returned_for_correction')<form method="POST" action="{{ route('approvals.requests.resubmit', $approval) }}" class="d-inline">@csrf<button class="btn btn-info btn-sm">Resubmit</button></form>@endif</div></div>

<div class="card"><div class="card-header">Timeline</div><div class="list-group list-group-flush">@forelse($approval->logs as $log)<div class="list-group-item"><strong>{{ strtoupper(str_replace('_', ' ', $log->action)) }}</strong> - {{ $log->remarks ?: '-' }}<div class="text-muted small">{{ $log->performer?->display_name ?? 'System' }} | {{ $log->performed_at?->format('Y-m-d H:i:s') }}</div></div>@empty<div class="list-group-item text-muted">No timeline actions yet.</div>@endforelse</div></div>
@endsection
